version: '3.8'

services:
    nginx:
        image: nginx:1.20-alpine
        ports:
            - 8000:80
        volumes:
            - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - frontend

    frontend:
        build:
            context: .
            dockerfile: .docker/frontend/Dockerfile
        working_dir: /app
        volumes:
            - ./:/app
        entrypoint: /entrypoint.sh
        command: npm run dev
